# Generated by Django 4.1.3 on 2022-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='branch',
            field=models.CharField(choices=[('ME', 'ME'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('CHE', 'CHE'), ('CE', 'CE'), ('MME', 'MME')], default='ME', max_length=5),
        ),
    ]
