# Generated by Django 4.1.3 on 2022-12-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_class_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=50)),
                ('dept', models.CharField(choices=[('ME', 'ME'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('CHE', 'CHE'), ('CE', 'CE'), ('MME', 'MME')], max_length=5)),
                ('position', models.CharField(default='Assistant Faculty', max_length=20)),
            ],
        ),
    ]
